#!/usr/bin/env python3
"""根據擷取的符號圖片，生成 50 題有圖片的 AIS 單選題"""
import json

# 格式：(圖片檔名, 正確答案, 選項A, B, C, D, 答案鍵)
SYMBOL_QS = [
  # ── Own Ship Symbols ─────────────────────────────────────
  ("SN243_sym_p4_1.png",
   "Own ship symbol (double circle at reference position)",
   "Own ship symbol — double circle at own ship's reference position",
   "Tracked radar target symbol",
   "AIS sleeping target",
   "Anchor symbol",
   "A"),
  ("SN243_sym_p4_3.png",
   "Own ship true scale outline",
   "Own ship radar antenna position",
   "Own ship true scale outline — oriented along own ship's heading",
   "AIS activated target outline",
   "Selected target outline",
   "B"),
  ("SN243_sym_p4_5.png",
   "Own ship radar antenna",
   "Own ship reference position",
   "Radar test target",
   "Own ship radar antenna — cross at physical location of antenna",
   "Own ship heading line end point",
   "C"),
  ("SN243_sym_p4_7.png",
   "Own ship heading line",
   "Own ship speed vector",
   "Own ship beam line",
   "EBL (Electronic Bearing Line)",
   "Own ship heading line — solid line thinner than speed vector",
   "D"),
  ("SN243_sym_p5_0.png",
   "Own ship past track",
   "AIS target past track",
   "Own ship predicted path",
   "Tidal stream indicator",
   "Own ship past track — thick line (primary) / thin line (secondary)",
   "D"),

  # ── Tracked Radar Target Symbols ─────────────────────────
  ("SN243_sym_p5_4.png",
   "Tracked target including dangerous target",
   "AIS activated target with vector",
   "Tracked target including dangerous target — circle with dashed course/speed vector",
   "Own ship outline with speed vector",
   "Lost target with vector",
   "B"),
  ("SN243_sym_p5_6.png",
   "Target in acquisition state",
   "Lost target symbol",
   "AIS sleeping target",
   "Selected target symbol",
   "Target in acquisition state — circle segments (bold/flashing/red for auto-acq.)",
   "D"),
  ("SN243_sym_p5_7.png",
   "Lost target",
   "AIS lost target",
   "Tracked target after CPA",
   "Lost target — triangle with bold solid cross, flashing until acknowledged",
   "Dangerous target symbol",
   "C"),
  ("SN243_sym_p5_8.png",
   "Selected target",
   "Activated AIS target",
   "Selected target — square indicated by its corners around activated target",
   "Associated target",
   "Acquired target",
   "B"),
  ("SN243_sym_p5_10.png",
   "Target past positions",
   "Tidal stream marks",
   "Own ship past track",
   "Radar time marks",
   "Target past positions — dots equally spaced by time",
   "D"),
  ("SN243_sym_p5_12.png",
   "Tracked target reference point",
   "Own ship reference point",
   "AIS target reference position",
   "Tracked target reference — CCRP indicator",
   "Cursor position marker",
   "D"),

  # ── AIS Target Symbols ────────────────────────────────────
  ("SN243_sym_p6_2.png",
   "AIS target (sleeping)",
   "AIS sleeping target — isosceles acute-angled triangle, oriented by heading or COG",
   "Radar tracked target",
   "Own ship symbol",
   "AIS AtoN symbol",
   "A"),
  ("SN243_sym_p6_9.png",
   "AIS activated target with course/speed vector",
   "AIS sleeping target with heading",
   "Own ship with speed vector",
   "AIS AtoN with bearing indicator",
   "AIS activated target — triangle with course/speed vector",
   "D"),
  ("SN243_sym_p7_1.png",
   "Selected AIS target",
   "Associated target",
   "Selected AIS target — square corners around activated AIS triangle",
   "AIS AtoN selected",
   "Acquired AIS target",
   "C"),
  ("SN243_sym_p7_3.png",
   "AIS Lost target",
   "AIS lost target — triangle with bold solid cross, flashing, no vector",
   "AIS dangerous target",
   "AIS target leaving range",
   "Lost AIS AtoN",
   "B"),
  ("SN243_sym_p7_5.png",
   "AIS target past positions",
   "AIS target past positions — dots equally spaced by time",
   "AIS track history line",
   "AIS route waypoints",
   "Own ship past track",
   "B"),
  ("SN243_sym_p7_7.png",
   "AIS Search and Rescue Vessel (SARV)",
   "AIS SAR aircraft",
   "AIS SAR transponder",
   "AIS Search and Rescue Vessel — circle with cross inside AIS vessel symbol",
   "AIS distress vessel",
   "D"),
  ("SN243_sym_p7_10.png",
   "AIS-SART (Search and Rescue Transponder)",
   "AIS MOB device",
   "AIS EPIRBsymbol",
   "AIS vessel in distress",
   "AIS-SART — specific symbol indicating AIS search and rescue transponder",
   "D"),
  ("SN243_sym_p7_12.png",
   "Selected AIS AtoN",
   "Activated AIS AtoN",
   "Lost AIS AtoN",
   "Selected AIS AtoN — square around activated AIS AtoN symbol",
   "Virtual AIS AtoN",
   "D"),
  ("SN243_sym_p7_16.png",
   "Lost AIS AtoN",
   "Sleeping AIS AtoN",
   "Lost AIS AtoN — AtoN symbol with cross, indicating lost Aid to Navigation",
   "Virtual AIS AtoN off position",
   "Missing physical AtoN indicator",
   "C"),

  # ── Associated Target Symbols ─────────────────────────────
  ("SN243_sym_p8_2.png",
   "Associated target (AIS symbol presentation)",
   "Associated target — activated AIS target symbol representing radar-associated target",
   "Tracked radar target",
   "AIS sleeping target",
   "Lost associated target",
   "A"),
  ("SN243_sym_p8_12.png",
   "Associated target (radar symbol alternative)",
   "AIS activated target alternative",
   "Tracked dangerous target",
   "Associated target alternative — activated AIS symbol modified with circle around triangle",
   "Associated target radar alternative — tracked radar symbol for associated target",
   "E"),

  # ── Navigation Symbols ────────────────────────────────────
  ("SN243_sym_p9_0.png",
   "Line of Position (LOP)",
   "Own ship heading indicator",
   "Danger bearing line",
   "Line of Position (LOP) — thin solid line from charted object towards own ship, labelled with time",
   "EBL fixed",
   "C"),
  ("SN243_sym_p9_1.png",
   "Monitored route",
   "Mandatory route",
   "Monitored route — route being actively monitored, distinct line style",
   "Planned route",
   "Trial manoeuvre route",
   "C"),
  ("SN243_sym_p9_3.png",
   "Planned route (alternate)",
   "Planned route (alternate) — alternative route presentation",
   "Monitored route",
   "Trial manoeuvre",
   "Mandatory route",
   "A"),
  ("SN243_sym_p9_4.png",
   "Trial manoeuvre",
   "Planned route simulation",
   "Danger bearing indicator",
   "Trial manoeuvre — projected path during trial manoeuvre calculation",
   "Simulation mode track",
   "D"),
  ("SN243_sym_p9_6.png",
   "Simulation mode",
   "Trial manoeuvre route",
   "Simulation mode — indicated when simulation is active on display",
   "Dead reckoning position",
   "Predicted route",
   "C"),
  ("SN243_sym_p9_7.png",
   "Cursor",
   "Cursor — crosshair or arrow indicating current cursor position on display",
   "Fixed reference mark",
   "Dropped EBL origin",
   "Event mark",
   "A"),
  ("SN243_sym_p9_8.png",
   "Range rings",
   "Variable Range Markers",
   "EBL bearing circles",
   "Guard zone boundary",
   "Range rings — concentric circles at fixed intervals from own ship",
   "D"),

  # ── Electronic Display Symbols ────────────────────────────
  ("SN243_sym_p10_2.png",
   "Electronic Bearing Line (EBL)",
   "Heading line",
   "Electronic Bearing Line (EBL) — dashed line from CCRP",
   "Danger bearing",
   "Parallel index line",
   "C"),
  ("SN243_sym_p10_4.png",
   "Acquisition / Activation area",
   "Guard zone",
   "Approach area",
   "Acquisition/Activation area — solid line boundary for target acquisition zone",
   "Exclusion zone",
   "D"),
  ("SN243_sym_p10_5.png",
   "Event mark",
   "Man overboard marker",
   "Waypoint symbol",
   "Position fix mark",
   "Event mark — rectangle with diagonal line, clarified by text (e.g. 'MOB')",
   "E"),
  ("SN243_sym_p10_6.png",
   "Tidal stream",
   "Tidal stream — single line with three arrowheads from charted position",
   "Current indicator",
   "Wind direction arrow",
   "Speed vector indicator",
   "B"),
  ("SN243_sym_p11_1.png",
   "Look-ahead alarm highlight",
   "Danger area indicator",
   "Caution area highlight",
   "Look-ahead alarm highlight — thick red polygon/poly-line on boundary causing alarm condition",
   "Guard zone alarm",
   "D"),
  ("SN243_sym_p11_5.png",
   "Danger bearing",
   "Danger bearing — bearing line indicating dangerous direction to be avoided",
   "EBL danger indicator",
   "Safety contour bearing",
   "Heading alarm indicator",
   "B"),

  # ── AIS AtoN Symbols (Table 5.1) ─────────────────────────
  ("SN243_sym_p18_8.png",
   "AIS AtoN default — Physical and Virtual",
   "Physical AIS AtoN — solid diamond; Virtual AIS AtoN — dotted diamond with crosshair",
   "Radar reflector buoy symbol",
   "AIS vessel at anchor",
   "IALA buoy symbol",
   "A"),
  ("SN243_sym_p18_9.png",
   "AIS AtoN fixed structure offshore",
   "AIS AtoN — fixed structure offshore/obstruction, solid diamond",
   "Radar fixed target symbol",
   "Platform symbol",
   "Oil rig indicator",
   "B"),
  ("SN243_sym_p18_12.png",
   "AIS AtoN Racon",
   "AIS AtoN — Racon (radar transponder beacon), type code 2",
   "Radar reflector symbol",
   "Radio beacon symbol",
   "DGNSS reference station",
   "A"),
  ("SN243_sym_p18_14.png",
   "AIS AtoN Emergency Wreck Marking Buoy",
   "Light buoy symbol",
   "Hazard marker",
   "AIS AtoN Emergency Wreck Marking Buoy — type code 4",
   "Danger zone marker",
   "C"),
  ("SN243_sym_p18_17.png",
   "AIS AtoN Cardinal North marks (Beacon and Floating)",
   "AIS AtoN Cardinal North — diamond with 2 triangles pointing upward on top",
   "AIS AtoN Cardinal South mark",
   "AIS AtoN isolated danger",
   "AIS AtoN safe water mark",
   "A"),

  # ── Meteorological / Special ──────────────────────────────
  ("SN243_sym_p14_1.png",
   "Signal station",
   "Light vessel symbol",
   "Weather station",
   "Signal station — diamond centred at reported position",
   "AIS AtoN special mark",
   "C"),
  ("SN243_sym_p15_1.png",
   "Berthing data",
   "Port entry symbol",
   "Berthing data — box with 'BERTH' inscribed, thick solid line, AIS AtoN colour",
   "Anchor berth indicator",
   "Mooring buoy symbol",
   "C"),
  ("SN243_sym_p13_1.png",
   "Tidal flow / Water level (AIS AtoN)",
   "Tidal flow and water level symbol — arrow for flow direction, gauge for water level",
   "Current speed indicator",
   "Depth sounding symbol",
   "Tide table reference mark",
   "A"),

  # ── VRM / Range symbols ───────────────────────────────────
  ("SN243_sym_p10_8.png",
   "Mariner-entered danger / User-defined danger",
   "Danger contour from chart",
   "Mariner-entered danger — user-defined object indicating navigational danger",
   "Look-ahead safety area",
   "Routing measure boundary",
   "B"),
  ("SN243_sym_p8_14.png",
   "Plotted position",
   "Plotted position — symbol for position obtained from terrestrial observations",
   "Dead reckoning position",
   "GPS fix position",
   "GNSS position fix",
   "A"),
  ("SN243_sym_p11_6.png",
   "Maritime Safety Information (MSI)",
   "MSI — box with 'MSI' inscribed, area covered by MSI region shown with sparse pattern",
   "Radar navigational warning",
   "AIS broadcast area",
   "Traffic separation scheme",
   "A"),
  ("SN243_sym_p12_1.png",
   "Meteorological information (weather station symbol)",
   "Weather buoy indicator",
   "Met-ocean data symbol",
   "Meteorological information — circle with 'W' inscribed, wind shaft with barbs",
   "Synoptic weather station",
   "D"),
  ("SN243_sym_p14_4.png",
   "Route broadcast information (AIS ASM)",
   "Route information — AIS ASM waypoints and leg lines with course labels",
   "Traffic separation scheme",
   "Recommended route",
   "Vessel traffic service boundary",
   "A"),
  ("SN243_sym_p16_0.png",
   "Area Notice (AIS ASM)",
   "Area Notice — box 'AN' for point, series of lines bounding area, filled with AN symbols",
   "No-go zone boundary",
   "Restricted area indicator",
   "Anchorage area boundary",
   "A"),
  ("SN243_sym_p16_1.png",
   "Air gap (AIS ASM)",
   "Water depth indicator",
   "Air gap — clearance between water surface and overhead structure",
   "Bridge clearance symbol",
   "Tidal gauge symbol",
   "C"),
]

# 有些選項 index 用了 "E"，fix to 4 options
def fix_q(entry):
    img, correct_desc, A, B, C, D, ans = entry
    if ans == "E":
        # Replace D with correct and reassign
        return img, correct_desc, A, B, C, correct_desc, "D"
    return entry

questions = []
for i, raw in enumerate(SYMBOL_QS, 1):
    img, correct_desc, A, B, C, D, ans = fix_q(raw)
    gid = f"AIS_SYM_115_{i}"
    questions.append({
        "year":    "115",
        "subject": "AIS符號識別",
        "question": f"{i}. The following symbol represents which navigation symbol?",
        "options":  {"A": A, "B": B, "C": C, "D": D},
        "answer":   ans,
        "image":    f"img/{img}",
        "groupId":  gid
    })

assert len(questions) == 50, f"應50題，實際{len(questions)}"
for q in questions:
    assert q["answer"] in q["options"], f"answer {q['answer']} not in options"

out = "/Users/yangjohn/MyQuiz/ais_sym_quiz_115.json"
with open(out, "w", encoding="utf-8") as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)
print(f"✅ 已生成 {len(questions)} 題（含圖）→ {out}")
